### PR TITLE
Sig bindings

### PR DESCRIPTION
**Pull request by gabizon103**
#190

### CODE REVIEW

**Comment by rachitnigam** [comment]
@gabizon103 any luck debugging the failing test?

**Comment by gabizon103** [comment]
@rachitnigam Haven't had much of a chance yet, but that's what I'm going to do today!

**Comment by rachitnigam** [comment]
@gabizon103 it is occurring to me that a possible problem can be that we're not defining the parameters in the `with` section use a subcomponent:
```
comp foo[#W](in: [G, G+1] #B) -> () with {
  #B = #W + 2
} { ... }
comp bar(...) {
  f := new foo[10]; // This should define both #W and #B
}
```

If the `#B` parameter is not defined within `bar`, then the port `f.in` is going to use an unknown parameter causing problems. In general, all parameters in the `with` section must be visible to the parent component.

**Comment by gabizon103** [comment]
> If the #B parameter is not defined within bar, then the port f.in is going to use an unknown parameter causing problems. In general, all parameters in the with section must be visible to the parent component.

Yeah I've come to this conclusion also. I am trying to figure out how to do this - `astconv` is pretty dense and I haven't looked at it much before this

**Comment by rachitnigam** [comment]
I've mucked up the PR because of this merge. If you're not working on it in the next hour or two, I can take a shot and you can try getting #263 PR merged in the meantime?

**Comment by gabizon103** [comment]
Sure, I'll work on #263!

**Comment by rachitnigam** [comment]
Subsumed by #294.

**Pull request closed without merging**
