### PR TITLE
Add foreign keys to ports and events

### PR DESCRIPTION
**Pull request by UnsignedByte**

### CODE REVIEW

**Comment by rachitnigam** [comment]
Looks like the tests are failing. The error message seems to be from IndexStore or something I think

**Comment by UnsignedByte** [comment]
> Looks like the tests are failing. The error message seems to be from IndexStore or something I think

Seems to be a traversal ordering issue, as this errors sometimes but not always.

**Comment by rachitnigam** [comment]
Indeed!

**Comment by rachitnigam** [comment]
LGTM!

**Pull request merged**
