### PR TITLE
Dockerfile updates

### PR DESCRIPTION
**Pull request by UnsignedByte**
Goals:
* Register `filament` stage in dockerfile
* Configure syntax highlighting for `.fil` files

### CODE REVIEW

**Comment by UnsignedByte** [comment]
Not working at the moment because `find_libpython` can't be found

**Comment by UnsignedByte** [comment]
> Not working at the moment because `find_libpython` can't be found

Done

**Comment by UnsignedByte** [comment]
Can probably merge this whenver, a very small change.

**Comment by rachitnigam** [comment]
Merge!

**Pull request merged**
